name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          # Remove pywin32 from requirements if not on Windows
          if [[ "$(uname -s)" != "MINGW"* && "$(uname -s)" != "CYGWIN"* && "$(uname -s)" != "MSYS"* ]]; then
            grep -v '^pywin32' requirements.txt > requirements-nopywin32.txt
            pip install -r requirements-nopywin32.txt
          else
            pip install -r requirements.txt
          fi

      - name: Run tests
        run: |
          # Run tests with pytest
          python --version
          pip --version
